name: 'GitHub Actions Variable Groups'
author: 'Brett Logan'
description: 'Allows for the central management of environment variables across multiple GitHub Actions projects.'
inputs:
  groups:
    description: A list of file or directory paths to load variables from
    required: true
  org:
    description: The GitHub org containing the repo
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: The repo where the GitHub issue exists
    required: true
  token:
    description: GitHub Admin PAT to open issues and comment
    required: true
    default: ${{ github.token }}
runs:
  using: node12
  main: dist/index.js
